### ISSUE TITLE
submit patch ?

### ISSUE THREAD

**Issue by mirlip** [mauge123/mechanical-blender#1]
Hi all,

Happy new year 2016 :)
You all did a great job and impressed many people during the Bconf. You can see here http://blenderartists.org/forum/showthread.php?385000-Blender-Grab-enhancements that the interest in your work is still there. Maybe you could drop some lines there and provide some builds to test and get feedback directly from the users?
Also, I know the reviewing process on the tracker can be hard sometime ( lot of fine-tuning and discussion to do to get a patch in master sometime), I think it would be good for you to get it committed.

Regards,
Mirlip

**Comment by bunterWolf** [comment]
subscribe! :)

**Comment by mirlip** [comment]
??? What do you mean ?

**Comment by bunterWolf** [comment]
I mean, I'm the same opinion as you ;)

I'm an industrial designer and i work a lot with blender, because its very fast and flexible. 
But it´s so hard to work precise and mechanical-blender looks perfect to get this too. 
But I cant get mechanical-blender running. Im not familiar with the blender compiling process... 
I tried a while, but get errors every time.. :(

**Comment by mauge123** [comment]
Thanks for your support ;)

The problem, is that the patch is based mainly on transform code, which is  a little messed, and affects lots of areas of blender, so applying to master or trunk is quite difficult, more if they consider a tool for artists, usually develop for and by artists. That's why i started a fork, basically to show up that some kinds of improvements are good for all. 

I'll update the diff https://developer.blender.org/D1501  because the problem is that maybe some changes on blender trunk will not success on applying it. Keeping the fork up to date with bf blender if quite difficult, because it's code receive lots of improvements and changes, quickly. But as said above, it's difficult to be accepted,  and it's not easy to do it with small diff's.

I tryed also to help improving the code, i mailed to bf-commiters about it with no reply.
http://lists.blender.org/pipermail/bf-committers/2015-November/046108.html

I can see interest on mechanical, architects users, but it does not give me the same impression of main developers, some maybe interested, but they are most focused and interested in other areas, and postpone the apply ot fhis features in a [near ? ] future.  I can think they consider or would like that this kind of tools "specific" for some users should be developed using add-ons. It's not possible at the moment, although i prefer to do it and develop on main code. Some companies also will not like 3rd party add-ons, because the stability around time is not guaranteed at all.

Next commit will try to solve the issue allowing to rotate the scene and moving around it while transform, removing the modal functionality changing the mouse buttons behavior.

If you have any problems on compile the source, maybe I can help you ;)
