### ISSUE TITLE
Shift does not slow down scaling or moevement

### ISSUE THREAD

**Issue by danilius** [mauge123/mechanical-blender#21]
When holding down Shift during a scaling or movement operation, the movement is not slowed down, as it is in Blender trunk.

**Comment by mauge123** [comment]
This was disabled, because was conflicting with the exit modal transform feature. In order to not change a lot of transform code, which could result a pain in merges of bf-trunk, we need the real cursor 2D position translation. Precision is working with "virtual mouse value" and this dues to not expected result on scene moves, so, currently if you move the scene, the distance of elements and mouse position is the same once the scene is fixed. If enabled the virtual mouse, this distance will change, and easly moved elements go out of the user view.

So a workaround should be find to get it working properly if really needed and useful. I can agree that in scale operations this may be needed for faster work (more if you are used to) although you can start the operation with the cursor not so close to transform origin, or change it on the fly using a snap point with B (base point). At this moment the base point must be an snap element, but will be a point in the screen sooner, which could replace the precision blender's default (allowing custom precision based on the distance from center to to a point. Precision it's now hardcoded).

**Comment by mauge123** [comment]
committed the workaround 43c521bcc3820142c997a9865bd38347f3e665da

It should work not in an accumulative way.

**Comment by danilius** [comment]
It's not really a showstopper, since really this branch is aimed at
mechanical precision, but the reason I mentioned it was because Blender is
superb for rapid sketching of concepts, so adding the ability to "CAD up"
an idea that was done "on the fly" takes Blender to a whole new level.

I will try to try this out today and report back.

Thanks for your swift response, clearly this project is very much alive and
you are very committed!

**Comment by danilius** [comment]
Seems to be working fine, thanks.
